deploy:
  provider: hugo
  skip_cleanup: true
  github_token: $DEPLOY_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch: src
